version: "3.8"

services:
  db:
    image: mariadb:10.4
    container_name: eshop-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cf9_eshop
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql 

  backend:
    build: ./backend
    container_name: eshop-backend
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/cf9_eshop
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  frontend:
    build: ./frontend
    container_name: eshop-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  db_data: