app.name=CF eshop
app.desc=Coding Factory 9 Full Stack Project
app.author=Karaiskou Anna Eirini

spring.application.name=cf9-eshop
spring.security.user.name=admin
spring.security.user.password=admin

jwt.secret-key=d22ec5dd-c1bd-40cd-bbec-49c1ccdd23df
jwt.expiration-time=86400000

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
# Settings for docker dist
spring.datasource.url=jdbc:mariadb://db:3306/cf9_eshop
spring.datasource.username=root
spring.datasource.password=root
# Settings for development
# spring.datasource.url=jdbc:mariadb://localhost:3306/cf9_eshop
# spring.datasource.username=root
# spring.datasource.password=

logging.level.root=INFO
logging.level.com.cf.karaiskou.eshop=INFO
# Console pattern
logging.pattern.console=%d{HH:mm:ss.SSS} %highlight(%-5level){INFO=blue, WARN=yellow, ERROR=red} [%thread] %cyan(%logger{36}) %n %msg%n
# XAMMP uses MariaDB MariaDB 10.4.32 
# Suppress Hibernate warnings for unsupported MariaDB versions
logging.level.org.hibernate.orm.core=ERROR

# For use during Development
# logging.level.org.hibernate.SQL=DEBUG
# logging.level.org.hibernate.tool.schema=DEBUG
